name: deepshell
version: '1.0.0'
summary: AI-powered Terminal Copilot for Linux Systems
description: |
  DeepShell is an intelligent terminal interface that combines 
  multiple AI models with a modern Linux terminal experience. 
  It serves as your AI-powered copilot, helping you navigate, 
  learn, and master the Linux command line.

grade: stable
confinement: strict
base: core22

apps:
  deepshell:
    command: bin/deepshell
    extensions: [gnome]
    plugs:
      - network
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gtk-3-themes
      - gsettings
      - network-bind

parts:
  deepshell:
    plugin: python
    source: .
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-vte-2.91
    python-packages:
      - langchain-core>=0.1.27
      - langchain-google-genai>=0.0.11
      - langchain-groq>=0.0.6
      - google-ai-generativelanguage>=0.4.0
      - google-generativeai>=0.3.2
      - groq>=0.4.2
      - requests
      - PyYAML
      - rich
      - tqdm 